// Generated by gencpp from file assignment_2_2022/goalTally.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_GOALTALLY_H
#define ASSIGNMENT_2_2022_MESSAGE_GOALTALLY_H

#include <ros/service_traits.h>


#include <assignment_2_2022/goalTallyRequest.h>
#include <assignment_2_2022/goalTallyResponse.h>


namespace assignment_2_2022
{

struct goalTally
{

typedef goalTallyRequest Request;
typedef goalTallyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct goalTally
} // namespace assignment_2_2022


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::assignment_2_2022::goalTally > {
  static const char* value()
  {
    return "c3b2d0cebb6acdd5ec152404b217af96";
  }

  static const char* value(const ::assignment_2_2022::goalTally&) { return value(); }
};

template<>
struct DataType< ::assignment_2_2022::goalTally > {
  static const char* value()
  {
    return "assignment_2_2022/goalTally";
  }

  static const char* value(const ::assignment_2_2022::goalTally&) { return value(); }
};


// service_traits::MD5Sum< ::assignment_2_2022::goalTallyRequest> should match
// service_traits::MD5Sum< ::assignment_2_2022::goalTally >
template<>
struct MD5Sum< ::assignment_2_2022::goalTallyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::goalTally >::value();
  }
  static const char* value(const ::assignment_2_2022::goalTallyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::goalTallyRequest> should match
// service_traits::DataType< ::assignment_2_2022::goalTally >
template<>
struct DataType< ::assignment_2_2022::goalTallyRequest>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::goalTally >::value();
  }
  static const char* value(const ::assignment_2_2022::goalTallyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::assignment_2_2022::goalTallyResponse> should match
// service_traits::MD5Sum< ::assignment_2_2022::goalTally >
template<>
struct MD5Sum< ::assignment_2_2022::goalTallyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::assignment_2_2022::goalTally >::value();
  }
  static const char* value(const ::assignment_2_2022::goalTallyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::assignment_2_2022::goalTallyResponse> should match
// service_traits::DataType< ::assignment_2_2022::goalTally >
template<>
struct DataType< ::assignment_2_2022::goalTallyResponse>
{
  static const char* value()
  {
    return DataType< ::assignment_2_2022::goalTally >::value();
  }
  static const char* value(const ::assignment_2_2022::goalTallyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_GOALTALLY_H
