// Generated by gencpp from file assignment_2_2022/goalTallyResponse.msg
// DO NOT EDIT!


#ifndef ASSIGNMENT_2_2022_MESSAGE_GOALTALLYRESPONSE_H
#define ASSIGNMENT_2_2022_MESSAGE_GOALTALLYRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace assignment_2_2022
{
template <class ContainerAllocator>
struct goalTallyResponse_
{
  typedef goalTallyResponse_<ContainerAllocator> Type;

  goalTallyResponse_()
    : num_reached(0)
    , num_cancelled(0)  {
    }
  goalTallyResponse_(const ContainerAllocator& _alloc)
    : num_reached(0)
    , num_cancelled(0)  {
  (void)_alloc;
    }



   typedef int32_t _num_reached_type;
  _num_reached_type num_reached;

   typedef int32_t _num_cancelled_type;
  _num_cancelled_type num_cancelled;





  typedef boost::shared_ptr< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> const> ConstPtr;

}; // struct goalTallyResponse_

typedef ::assignment_2_2022::goalTallyResponse_<std::allocator<void> > goalTallyResponse;

typedef boost::shared_ptr< ::assignment_2_2022::goalTallyResponse > goalTallyResponsePtr;
typedef boost::shared_ptr< ::assignment_2_2022::goalTallyResponse const> goalTallyResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator2> & rhs)
{
  return lhs.num_reached == rhs.num_reached &&
    lhs.num_cancelled == rhs.num_cancelled;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator1> & lhs, const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace assignment_2_2022

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c3b2d0cebb6acdd5ec152404b217af96";
  }

  static const char* value(const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc3b2d0cebb6acdd5ULL;
  static const uint64_t static_value2 = 0xec152404b217af96ULL;
};

template<class ContainerAllocator>
struct DataType< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "assignment_2_2022/goalTallyResponse";
  }

  static const char* value(const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 num_reached\n"
"int32 num_cancelled\n"
"\n"
;
  }

  static const char* value(const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num_reached);
      stream.next(m.num_cancelled);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct goalTallyResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::assignment_2_2022::goalTallyResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::assignment_2_2022::goalTallyResponse_<ContainerAllocator>& v)
  {
    s << indent << "num_reached: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_reached);
    s << indent << "num_cancelled: ";
    Printer<int32_t>::stream(s, indent + "  ", v.num_cancelled);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASSIGNMENT_2_2022_MESSAGE_GOALTALLYRESPONSE_H
